### ISSUE TITLE
Computational time issue in antsJointFusion 

### ISSUE THREAD

**Issue by leomimo** [stnava/ANTs#284] opened 2016-03-02 10:59 UTC
Hello,
I recently switched from jointfusion to antsJointFusion and I noticed that the computational time dramatically increased, i.e from ~2h to more than 70h on a single core machine, using exactly the same target, inputs and options. The results are slightly different but I cannot really tell which one was better.
I downloaded and compiled the code from GitHub the 26th of February. Is it a problem of optimization or antsJointFusion is doing something different from its predecessor?
Thank you very much for your help.
Matteo

**Comment by ntustison** [comment] 2016-03-02 14:25
One of the differences between the two implementations (and what probably explains the time difference) is the original ``jointfusion`` employs a simple voxelwise exclusion criteria which is not used by the most recent implementation.  Specifically, as ``jointfusion`` iterates through the image, if the current voxel does not have any non-zero labels from any of the atlases at that voxel, then it immediately moves on to the next voxel.  This assumption is not necessarily valid for every use case in the new code since ``antsJointFusion`` also incorporates joint intensity fusion.  However, this is easily mimicked in the new code by supplying a mask (``-x`` option) derived as a voxelwise ``or`` operation of all the warped atlas segmentations.  This is what we do in ``antsJointLabelFusion.sh`` as illustrated [here](https://github.com/stnava/ANTs/blob/master/Scripts/antsJointLabelFusion.sh#L864-L873).  

There will be some differences in the results and this is caused by some implementation choices.  For example, part of the algorithm is to do a local patch-wise search to find the most similar patch to account for misalignments.  The most convenient manner to do this is to iterate through the local search neighborhood as ITK specifies a neighborhood with the first "neighbor" being in the upper left corner (for 2-D).  However, the results are influenced based on the chosen search pattern and this one is particular bad as it artificially biases the results to that corner.  A better way is to actually bias the results based on confidence in the registration.  In other words, the search algorithm should look first at the voxels closest to the current voxel followed by those further away.

**Comment by ntustison** [comment] 2016-03-02 15:28
Closing this for now.  Might need to reopen if computational discrepancies aren't explained by the above response.

**Closed by ntustison** 2016-03-02 15:28 UTC
